### ISSUE TITLE
Title is undefined - angular6

### ISSUE THREAD

**Issue by ajaydjalexander** [Jamaks/ng-fullcalendar#99]
Hello,

I am getting "June 1 2018undefinedundefined – undefinedundefinedundefined" on title when I build on production using angular6.

**Comment by Jamaks** [comment]
Hi, this issue not in angular 5?

**Comment by andrejm7** [comment]
Yes.. Angular 5 also... see July 2, 2018undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined

**Comment by Jamaks** [comment]
Hi! please see https://jamaks.github.io/ng-fullcalendar-demo/dist/ and https://jamaks.github.io/ng-fullcalendar-demo

**Comment by dgbrunoh** [comment]
Hi @Jamaks,

I'm still having this issue when I try to use with the fullcalendar-scheduler plugin.
I've checked the **ng-fullcalendar.js** file in the package and I could fix replacing the line 3 from:
`import fullcalendar from 'fullcalendar';`
to:
`import fullcalendar from 'fullcalendar-scheduler';`

The issue happens because the **fullcalendar-scheduler** is already loading **fullcalendar** module.

**Comment by newcreativegamer** [comment]
I'm getting this as well and those link above don't work. Anyone have any ideas how to solve it?

**Comment by vrt2015** [comment]
@ajaydjalexander Were you able to resolve the issue?
The links provided are not working.
